/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Accounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ConnectorEvent": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ConnectorTemplates": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}

import "sst"
export {}