name: local
variables:
  - secret: true
    name: DebugUsername
    description: ""
  - secret: true
    name: DebugPassword
    description: ""
  - secret: true
    name: AwsAccountId
    description: ""
  - secret: true
    name: ApiBase
    description: ""
