name: local
variables:
  - name: ApiBase
    value: https://c7tgagve3kc3exze5zh6q6hl3u0lmqth.lambda-url.ap-southeast-2.on.aws
    description: ""
  - secret: true
    name: DebugUsername
  - secret: true
    name: DebugPassword
