import type { CognitoAuthTexts } from "./types";

export const defaultCognitoAuthTexts: CognitoAuthTexts = {
	signInTitle: "Sign in",
	signInSubtitle: "Use your account credentials to continue.",
	signUpTitle: "Create account",
	signUpSubtitle: "Enter your details to create an account.",
	confirmSignUpTitle: "Verify email",
	confirmSignUpSubtitle: "Enter the code sent to your email.",
	forgotPasswordTitle: "Reset password",
	forgotPasswordSubtitle: "Enter your email to receive a reset code.",
	confirmForgotPasswordTitle: "Set new password",
	confirmForgotPasswordSubtitle: "Use your reset code to set a new password.",
	newPasswordRequiredTitle: "Set new password",
	newPasswordRequiredSubtitle: "Set a new password to finish signing in.",
	nameLabel: "Full name",
	emailLabel: "Email",
	passwordLabel: "Password",
	newPasswordLabel: "New password",
	confirmPasswordLabel: "Confirm password",
	codeLabel: "Verification code",
	signInButton: "Sign in",
	signUpButton: "Create account",
	confirmSignUpButton: "Confirm account",
	sendResetCodeButton: "Send reset code",
	resetPasswordButton: "Reset password",
	setPasswordButton: "Set password",
	resendCodeButton: "Resend code",
	forgotPasswordLink: "Forgot password?",
	signUpLink: "Sign up",
	backToSignInLink: "Sign in",
	verificationCodeSent:
		"Verification code sent. Check your email to continue.",
	accountVerified: "Account verified. Sign in to continue.",
	resetCodeSent: "Reset code sent. Check your email to continue.",
	passwordUpdated: "Password updated. Sign in with your new password.",
	codeResent: "Another code is on the way.",
	resetCodeResent: "Another reset code is on the way.",
	passwordSet: "Password set.",
	genericError: "Something went wrong.",
	requiredMessage: "Required",
	invalidEmailMessage: "Enter a valid email",
	minPasswordMessage: "Password must be at least {minimumLength} characters",
	passwordLowercaseMessage: "Password must include a lowercase letter",
	passwordNumberMessage: "Password must include a number",
	passwordSymbolMessage: "Password must include a symbol",
	passwordUppercaseMessage: "Password must include an uppercase letter",
	passwordMismatchMessage: "Passwords must match"
};
